# These are supported funding model platforms

github: Mailwurm
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # ko_fi
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # liberapay
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # custom
